#!/bin/bash

set -e

echo "Starting Synapse setup..."

SYNAPSE_DIR="$HOME/synapse"

# Create directory
echo "Creating Synapse directory..."
mkdir -p "$SYNAPSE_DIR"
cd "$SYNAPSE_DIR"

echo "Creating .env File with AutoGenerated Password..."
cat <<EOF > .env
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
EOF

# Create docker-compose.yml
echo "Creating docker-compose.yml..."

cat <<EOF > docker-compose.yml
services:
  synapse:
    container_name: synapse
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    image: docker.io/matrixdotorg/synapse:latest
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - ./files:/data
    depends_on:
      - postgres-db
    ports:
      - 8008:8008

  postgres-db:
    container_name: postgres-db
    image: docker.io/postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./schemas:/var/lib/postgresql/data
  cinny:
    container_name: cinny
    image: ajbura/cinny:latest
    ports:
      - 9002:80
EOF

echo "docker-compose.yml created."

# Create required folders
mkdir -p files
mkdir -p schemas

# Ask for server name
read -p "Enter your Matrix server name (example: matrix.example.com): " SERVER_NAME

echo "Generating Synapse configuration..."

sudo docker compose run --rm \
  -e SYNAPSE_SERVER_NAME="$SERVER_NAME" \
  -e SYNAPSE_REPORT_STATS=yes \
  synapse generate

echo "Starting Synapse containers..."
sudo docker compose up -d

echo "Waiting for Synapse container to initialize..."
sleep 10

echo ""
echo "Create admin user:"
echo "Run the following command:"
echo ""
echo "docker exec -it synapse register_new_matrix_user http://localhost:8008 -c /data/homeserver.yaml"
echo ""

docker compose run --rm -e SYNAPSE_SERVER_NAME=$SERVER_NAME synapse generate

# Modify config
sed -i '/registration_shared_secret:/d' files/homeserver.yaml
sed -i '/report_stats:/i enable_registration: true\nenable_registration_without_verification: true' files/homeserver.yaml

# Start server
docker compose up -d
echo "Synapse setup complete."
echo "Cinny setup complete."
echo "Create your admin user"

docker exec -it synapse register_new_matrix_user http://localhost:8008 -c /data/homeserver.yaml

echo "You can now access Matrix via Cinny on http://$HOSTNAME:9002"
