#!/bin/bash
set -e

echo "Starting Matrix setup..."

SYNAPSE_DIR="$HOME/matrix"

# Create directory
echo "Creating Matrix directory..."
mkdir -p "$SYNAPSE_DIR"
cd "$SYNAPSE_DIR"

echo "Creating .env File with AutoGenerated Password..."
cat <<EOF > .env
POSTGRES_USER=matrix
POSTGRES_PASSWORD=$(openssl rand -base64 16)
EOF

# Create docker-compose.yml
echo "Creating docker-compose.yml..."

cat <<EOF > docker-compose.yml
services:
  synapse:
    container_name: matrix-synapse-server
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    image: docker.io/matrixdotorg/synapse:latest
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_REPORT_STATS=yes
    volumes:
      - ./files:/data
    depends_on:
      - postgres-db
    ports:
      - 8008:8008

  postgres-db:
    container_name: matrix-db
    image: docker.io/postgres:15-alpine
    environment:
      - POSTGRES_USER=\${POSTGRES_USER}
      - POSTGRES_PASSWORD=\${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./schemas:/var/lib/postgresql/data
  cinny:
    container_name: matrix-front-end
    image: ajbura/cinny:latest
    ports:
      - 9002:80
EOF

echo "docker-compose.yml created."

# Create required folders
mkdir -p files
mkdir -p schemas

# Ask for server name
read -p "Enter your Matrix server name (example: matrix.example.com): " SERVER_NAME

echo "Generating Matrix configuration..."

sudo docker compose run --rm \
  -e SYNAPSE_SERVER_NAME="$SERVER_NAME" \
  -e SYNAPSE_REPORT_STATS=yes \
  synapse generate

echo "Starting Matrix containers..."
sudo docker compose up -d

echo "Waiting for Matrix container to initialize..."
sleep 10

echo ""
echo "Create admin user:"
echo "Run the following command:"
echo ""
echo "docker exec -it synapse register_new_matrix_user http://localhost:8008 -c /data/homeserver.yaml"
echo ""

docker compose run --rm -e SYNAPSE_SERVER_NAME=$SERVER_NAME synapse generate

# Modify config
cat <<EOF | sudo tee -a homeserver.yaml > /dev/null
enable_registration: true
enable_registration_without_verification: true
EOF

# Start server
docker compose up -d
echo "Synapse setup complete."
echo "Cinny setup complete."
echo "Create your admin user"

docker exec -it synapse register_new_matrix_user http://localhost:8008 -c /data/homeserver.yaml

echo "Updating the master .env records..."

SOURCE=".env"
DEST="/home/admin/.env"

if [ -f "$DEST" ]; then
    echo "Destination File exists..."
    echo "#####MATRIX#####" >> "$DEST"
    cat "$SOURCE" >> "$DEST"
else
    echo "File does not exist..."
    echo "#####MATRIX#####" >> "$DEST"

    cat "$SOURCE" >> "$DEST"
    echo "Master .env file created..."
fi

echo "You can now access Matrix via Cinny on http://$HOSTNAME:9002"
